package com.isoftstone.kaoqin.po;

public class NdsChinese {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nds_chinese.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nds_chinese.info_create_time
     *
     * @mbggenerated
     */
    private String infoCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nds_chinese.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nds_chinese.recommend
     *
     * @mbggenerated
     */
    private Integer recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nds_chinese.publisher
     *
     * @mbggenerated
     */
    private String publisher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nds_chinese.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nds_chinese.releaser
     *
     * @mbggenerated
     */
    private String releaser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nds_chinese.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nds_chinese.chinese_level
     *
     * @mbggenerated
     */
    private String chineseLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nds_chinese.intro
     *
     * @mbggenerated
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nds_chinese.old_name
     *
     * @mbggenerated
     */
    private String oldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nds_chinese.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nds_chinese.size
     *
     * @mbggenerated
     */
    private String size;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nds_chinese.id
     *
     * @return the value of nds_chinese.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nds_chinese.id
     *
     * @param id the value for nds_chinese.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nds_chinese.info_create_time
     *
     * @return the value of nds_chinese.info_create_time
     *
     * @mbggenerated
     */
    public String getInfoCreateTime() {
        return infoCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nds_chinese.info_create_time
     *
     * @param infoCreateTime the value for nds_chinese.info_create_time
     *
     * @mbggenerated
     */
    public void setInfoCreateTime(String infoCreateTime) {
        this.infoCreateTime = infoCreateTime == null ? null : infoCreateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nds_chinese.date
     *
     * @return the value of nds_chinese.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nds_chinese.date
     *
     * @param date the value for nds_chinese.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nds_chinese.recommend
     *
     * @return the value of nds_chinese.recommend
     *
     * @mbggenerated
     */
    public Integer getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nds_chinese.recommend
     *
     * @param recommend the value for nds_chinese.recommend
     *
     * @mbggenerated
     */
    public void setRecommend(Integer recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nds_chinese.publisher
     *
     * @return the value of nds_chinese.publisher
     *
     * @mbggenerated
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nds_chinese.publisher
     *
     * @param publisher the value for nds_chinese.publisher
     *
     * @mbggenerated
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nds_chinese.name
     *
     * @return the value of nds_chinese.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nds_chinese.name
     *
     * @param name the value for nds_chinese.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nds_chinese.releaser
     *
     * @return the value of nds_chinese.releaser
     *
     * @mbggenerated
     */
    public String getReleaser() {
        return releaser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nds_chinese.releaser
     *
     * @param releaser the value for nds_chinese.releaser
     *
     * @mbggenerated
     */
    public void setReleaser(String releaser) {
        this.releaser = releaser == null ? null : releaser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nds_chinese.url
     *
     * @return the value of nds_chinese.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nds_chinese.url
     *
     * @param url the value for nds_chinese.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nds_chinese.chinese_level
     *
     * @return the value of nds_chinese.chinese_level
     *
     * @mbggenerated
     */
    public String getChineseLevel() {
        return chineseLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nds_chinese.chinese_level
     *
     * @param chineseLevel the value for nds_chinese.chinese_level
     *
     * @mbggenerated
     */
    public void setChineseLevel(String chineseLevel) {
        this.chineseLevel = chineseLevel == null ? null : chineseLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nds_chinese.intro
     *
     * @return the value of nds_chinese.intro
     *
     * @mbggenerated
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nds_chinese.intro
     *
     * @param intro the value for nds_chinese.intro
     *
     * @mbggenerated
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nds_chinese.old_name
     *
     * @return the value of nds_chinese.old_name
     *
     * @mbggenerated
     */
    public String getOldName() {
        return oldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nds_chinese.old_name
     *
     * @param oldName the value for nds_chinese.old_name
     *
     * @mbggenerated
     */
    public void setOldName(String oldName) {
        this.oldName = oldName == null ? null : oldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nds_chinese.type
     *
     * @return the value of nds_chinese.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nds_chinese.type
     *
     * @param type the value for nds_chinese.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nds_chinese.size
     *
     * @return the value of nds_chinese.size
     *
     * @mbggenerated
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nds_chinese.size
     *
     * @param size the value for nds_chinese.size
     *
     * @mbggenerated
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }
}